# Generated by Django 2.1.2 on 2019-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Artista',
            new_name='artista',
        ),
    ]
